import React, { useState, useEffect } from 'react';
import api from '../../services/api';
import { useToast } from '../../context/ToastContext';
import { Badge } from '../../components/common/Badge';
import { 
  FileText, 
  Pill, 
  Sparkles, 
  Clock, 
  Calendar, 
  AlertCircle, 
  HeartHandshake, 
  Bell, 
  Activity,
  Bot,
  CheckCircle2
} from 'lucide-react';

export const MyPrescriptionsPage = ({ onBookFollowup }) => {
  const toast = useToast();
  const [prescriptions, setPrescriptions] = useState([]);
  const [reminders, setReminders] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchData = async () => {
    setLoading(true);
    try {
      const [rxRes, remRes] = await Promise.all([
        api.get('/visits/prescriptions/my'),
        api.get('/visits/reminders/my'),
      ]);
      setPrescriptions(rxRes.data);
      setReminders(remRes.data);
    } catch (err) {
      toast.error('Failed to load prescriptions and medication reminders.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Header */}
      <div>
        <div className="inline-flex items-center gap-2 text-xs font-semibold text-purple-400 uppercase tracking-wider mb-1">
          <Pill className="w-4 h-4" />
          <span>Patient Health Records</span>
        </div>
        <h1 className="text-3xl font-bold text-white font-['Outfit']">
          Prescriptions &amp; AI Follow-up Care
        </h1>
        <p className="text-sm text-slate-400 mt-1">
          Patient-friendly clinical translations generated by Groq LLaMA 3.3 and scheduled medication alerts
        </p>
      </div>

      {/* Active Medication Reminders Ribbon */}
      {reminders.length > 0 && (
        <div className="glass-panel p-6 rounded-2xl border border-purple-500/30 bg-gradient-to-r from-purple-950/60 via-indigo-950/40 to-[#0e0520] space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2.5">
              <div className="p-2 rounded-xl bg-purple-900/60 text-purple-300">
                <Bell className="w-5 h-5 animate-bounce" />
              </div>
              <div>
                <h3 className="text-base font-bold text-white font-['Outfit']">Active Medication Alerts</h3>
                <p className="text-xs text-slate-400">Scheduled by APScheduler based on prescription frequency</p>
              </div>
            </div>
            <Badge variant="cyan">{reminders.length} Active Reminders</Badge>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 pt-2">
            {reminders.map((rem) => (
              <div
                key={rem.id}
                className="p-3.5 rounded-xl bg-[#0d041c] border border-purple-900/60 flex items-center justify-between"
              >
                <div className="flex items-center gap-3">
                  <Pill className="w-4 h-4 text-purple-400" />
                  <div>
                    <h4 className="text-xs font-bold text-white">{rem.medicine_name}</h4>
                    <p className="text-[11px] text-slate-400">{rem.dosage} • {rem.frequency}</p>
                  </div>
                </div>
                <span className="text-[10px] font-mono font-semibold px-2 py-0.5 rounded bg-purple-950 border border-purple-700 text-purple-300">
                  {rem.reminder_time}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Prescriptions List */}
      {loading ? (
        <div className="space-y-6">
          {[1, 2].map((i) => (
            <div key={i} className="glass-panel p-8 rounded-2xl h-64 animate-pulse" />
          ))}
        </div>
      ) : prescriptions.length === 0 ? (
        <div className="glass-panel p-12 rounded-2xl text-center space-y-4">
          <FileText className="w-12 h-12 text-purple-400/50 mx-auto" />
          <h3 className="text-lg font-bold text-white font-['Outfit']">No Prescriptions Issued Yet</h3>
          <p className="text-xs text-slate-400">Your doctor will issue medical summaries and prescriptions here after consultation.</p>
        </div>
      ) : (
        <div className="space-y-8">
          {prescriptions.map((rx) => {
            const appointment = rx.appointment || {};
            const summary = appointment.visit_summary;
            const doc = appointment.doctor || {};
            const docUser = doc.user || {};

            return (
              <div
                key={rx.id}
                className="glass-panel p-6 sm:p-8 rounded-3xl border border-purple-900/50 space-y-6 shadow-[0_4px_30px_rgba(0,0,0,0.4)]"
              >
                {/* Header: Diagnosis & Doctor */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-purple-950">
                  <div>
                    <span className="text-xs text-purple-400 font-semibold uppercase tracking-wider block mb-1">
                      Clinical Consultation Record
                    </span>
                    <h3 className="text-xl font-bold text-white font-['Outfit']">
                      Diagnosis: {rx.diagnosis}
                    </h3>
                    <div className="flex items-center gap-2 text-xs text-slate-400 mt-1">
                      <span>Doctor: {docUser.full_name || 'Dr. Medical Specialist'}</span>
                      <span>• Issued: {new Date(rx.created_at).toLocaleDateString([], { dateStyle: 'long' })}</span>
                    </div>
                  </div>

                  {rx.followup_date && (
                    <div className="p-3 rounded-xl bg-purple-950/60 border border-purple-800/40 text-xs text-right">
                      <span className="text-slate-400 block">Recommended Follow-up</span>
                      <span className="text-cyan-300 font-bold font-mono">
                        {new Date(rx.followup_date).toLocaleDateString([], { dateStyle: 'medium' })}
                      </span>
                    </div>
                  )}
                </div>

                {/* Groq LLaMA 3.3 AI Patient Summary Box */}
                {summary && summary.ai_patient_summary && (
                  <div className="p-6 rounded-2xl bg-gradient-to-br from-[#1a0a38] to-[#120525] border border-purple-500/40 space-y-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <div className="p-1.5 rounded-lg bg-purple-600/30 text-purple-300">
                          <Bot className="w-4 h-4" />
                        </div>
                        <h4 className="text-sm font-bold text-white font-['Outfit']">
                          AI Patient-Friendly Consultation Summary
                        </h4>
                      </div>
                      <Badge variant="primary" size="sm">Groq LLaMA 3.3 AI</Badge>
                    </div>

                    <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
                      {summary.ai_patient_summary}
                    </p>

                    {summary.ai_medication_schedule && (
                      <div className="pt-2 border-t border-purple-900/50">
                        <span className="text-xs font-bold text-purple-300 block mb-1">Medication Schedule &amp; Timing:</span>
                        <p className="text-xs text-slate-300 leading-relaxed">{summary.ai_medication_schedule}</p>
                      </div>
                    )}

                    {summary.ai_followup_steps && (
                      <div className="pt-2 border-t border-purple-900/50">
                        <span className="text-xs font-bold text-cyan-300 block mb-1">Next Steps &amp; Watchouts:</span>
                        <p className="text-xs text-slate-300 leading-relaxed">{summary.ai_followup_steps}</p>
                      </div>
                    )}
                  </div>
                )}

                {/* Structured Medications Table / Cards */}
                <div>
                  <h4 className="text-xs font-bold uppercase tracking-wider text-purple-300 mb-3 flex items-center gap-1.5">
                    <Pill className="w-4 h-4 text-purple-400" />
                    <span>Prescribed Medications ({rx.medications?.length || 0})</span>
                  </h4>

                  <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                    {(rx.medications || []).map((med, idx) => (
                      <div
                        key={idx}
                        className="p-4 rounded-xl bg-[#0c0418] border border-purple-900/60 space-y-2"
                      >
                        <div className="flex items-center justify-between">
                          <h5 className="text-sm font-bold text-white">{med.name}</h5>
                          <span className="text-xs font-mono font-bold text-emerald-400">{med.dosage}</span>
                        </div>
                        <p className="text-xs text-purple-300 font-medium">Frequency: {med.frequency}</p>
                        {med.duration_days && (
                          <p className="text-xs text-slate-400">Duration: {med.duration_days} days</p>
                        )}
                        {med.instructions && (
                          <p className="text-xs text-slate-400 italic">Instructions: {med.instructions}</p>
                        )}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Doctor Advice Notes */}
                {rx.advice && (
                  <div className="p-4 rounded-xl bg-purple-950/20 border border-purple-900/40 text-xs">
                    <span className="font-bold text-slate-300 block mb-1">Doctor's Clinical Advice:</span>
                    <p className="text-slate-400 leading-relaxed">{rx.advice}</p>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
